### ISSUE TITLE
Error al querer curar la factura en Odo 16.0

### ISSUE THREAD

**Issue by Maurix09** [ingadhoc/odoo-argentina-ce#49]
> NO ME DEJA FACTURAR
>
> ODOO16
> 
> *Pasos para reproducir:*
> 
>  1. Instalo los certificados
>  2. Creo el diario de facturacion digital, con Electronic Invoice (Web Service), porque el que dice Facturacion en linea desaparecen los botones de prueba de conexión y cuando cree una factura, fue como si fuera una factura sin CAE...
>  3. Cuando creo la factura sale error
> 
> *Lo que pasa actualmente:*
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1612, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1809, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-argentina-ce/l10n_ar_afipws_fe/models/account_journal.py", line 85, in action_get_connection
    self.company_id.get_connection(afip_ws).connect()
  File "/opt/odoo/odoo-argentina-ce/l10n_ar_afipws/models/res_company.py", line 147, in get_connection
    connection = self._create_connection(afip_ws, environment_type)
  File "/opt/odoo/odoo-argentina-ce/l10n_ar_afipws/models/res_company.py", line 166, in _create_connection
    auth_data = self.authenticate(afip_ws, cert, pkey, wsdl=login_url)
  File "/opt/odoo/odoo-argentina-ce/l10n_ar_afipws/models/res_company.py", line 205, in authenticate
    from pyafipws.wsaa import WSAA
ModuleNotFoundError: No module named 'pyafipws.wsaa'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://200.73.168.2:7009/web/assets/267-385b4f9/web.assets_backend.min.js:967:163)
    at XMLHttpRequest.<anonymous> (http://200.73.168.2:7009/web/assets/267-385b4f9/web.assets_backend.min.js:974:13)

 
> *Lo que debe pasar:*
> 
>  - Crear la factura y recibir su CAE
>
> *Analisis profunda:*
>
No entiendo bien que debo poner en el nuevo campo que dice Caea journal!!! que es, y como funciona? que debo poner ahi?

**Comment by filoquin** [comment]
Hola, tenes un error en el deploy de tu server. 
ModuleNotFoundError: No module named 'pyafipws.wsaa'
Verifica la instalacion de pyafipws

El modulo CAEA solo lo tenes que usar si dispones de autorizacion para emitir CAEA
