### ISSUE TITLE
[13.0] Can't issue new certificate

### ISSUE THREAD

**Issue by sotolucas** [ingadhoc/odoo-argentina-ce#5]
> **Can't issue new certificate**
>
> *Version afectada:*
> 
>  - 13.0
> 
> *Pasos para reproducir:*
> 
>  1. create new db (clean, just l10n_ar).
>  2. install l10n_ar (all external_dependencies an dependency modules installed).
>  3. try to create a new certificate and save (completing all fields previously).
> 
> *Lo que pasa actualmente:*
> 
>  - Throws an error:
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 2902, in read
    self._read(stored_fields)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3044, in _read
    field.read(fetched)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 2930, in read
    lines = comodel.search(domain, limit=self.limit)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 1618, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4383, in _search
    self._apply_ir_rules(query, 'read')
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4172, in _apply_ir_rules
    where_clause, where_params, tables = Rule.domain_get(self._name, mode)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_rule.py", line 188, in domain_get
    query = self.env[model_name].sudo()._where_calc(dom, active_test=False)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4111, in _where_calc
    e = expression.expression(domain, self)
  File "/opt/odoo/custom/src/odoo/odoo/osv/expression.py", line 675, in __init__
    self.parse()
  File "/opt/odoo/custom/src/odoo/odoo/osv/expression.py", line 856, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'company_id' in leaf "<osv.ExtendedLeaf: ('company_id', 'in', [1]) on afipws_certificate (ctx: )>"
```
> 
> *Lo que debe pasar:*
> 
>  - Just issue the certificate.
>

**Comment by sotolucas** [comment]
@FedericoGregori pudiste hacer funcionar el fork?

**Comment by FedericoGregori** [comment]
@sotolucas Hola Lucas, hice el fork para ir leyendo el código y quería adaptar unas cosas pequeñas, pero entre hoy o mañana recién pensaba hacerlo. Lo pruebo y te aviso!

**Comment by jjscarafia** [comment]
fixed here https://github.com/ingadhoc/odoo-argentina-ce/pull/6
As the rule has noupdate you need to manually modify it or make a PR adding a migration script to force update of the role

**Comment by sotolucas** [comment]
@jjscarafia considering I'm the first to try I'll make it manually.
Thanks :1st_place_medal:
